feat: Kubernetes Operator  (#153)
* feat: KubeOps

* Add solution explorer.exe

* Ran dotnet format

* Delete dockerfile

* Remove unneeded library

* Delete file

* Remove log

* Update Operator.csproj to not include the autogenerated docker file an additional dependency needed

* Updated Program.cs by utilizing aspnetcore-6.0 top level feature to reduce the amount of code used in program.cs and startup.cs

* Remove unused lines

* Update namespace

* Add model for structs used in an entity

* Remove structs from entity

* Update group name

* Add comment for element in Appplication enetity

* Fix comment for applciation entity

* Remove whitespace

* Add comment to public elements

* Add comments to ColumnSpec

* Add comments for ModelSpec

* Add comment to validatespecs

* Ran dotnet format

* Rename

* update ns

* Upadte namespace

* Remove ServiceUris since it has no relation to this current PR

* Update NS

* move struct

* move struct

* Update NS

* Update NS

* Update namespace

* Remove allow nullable

* Update by removing allowing nullable

* Upodate nullable values

* Add defaults

* Better C# namespace syntax

* Namespace did not correspond to file location.
The file location is Project specific and folders outside of the project should not be included as a prefix to the namespace.
If those namespaces are desired, then the folder structure needs to exist inside of the project.

* Dotnet format

* Add constructors

* ColumnSpec.cs(16,12): error CS0843: Auto-implemented property 'ColumnSpec.Validate' must be fully assigned before control is returned
to the caller.

* Namespace

* Updat to dialect variable to make it not nullable

* Remove allowing nullable in applicationspec

* Update CRD

* Remove old crd

* Spacing

* Add default values

* Remove nullable list

* Typo

* Update crd

* Add default value for ModelSpec.cs

* Format

* Add comment

Co-authored-by: Keith Becker <keith.becker@recro.com>
Co-authored-by: Baban Faraj <baban.faraj@recro.com>